BigQ/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from main import views

urlpatterns = [
    path("about-us/", TemplateView.as_view(template_name='about_us.html'), name="about_us"),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('contact-us/', views.ContactUsView.as_view(), name='contact_us')
]

main/models.py
from django.db import models


# Create your models here.
class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)



class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48, unique=True)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    objects = ActiveManager()


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )

    image = models.ImageField(upload_to="product-image")

    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )


class ProductTag(models.Model):
    products = models.ManyToManyField(Product, blank=True)
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging


logger = logging.getLogger(__name__)


class ContactForm (forms.Form):
    name = forms.CharField(label='Name', max_length=200, required=True)
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(label='Message', max_length=2000, widget=forms.Textarea, required=True)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From {0} \nEmail: {1} \nMessage:\n   {2}".format(
            self.cleaned_data['name'],
            self.cleaned_data['email'],
            self.cleaned_data['message']
        )
        send_mail(
            "Site message",
            message,
            "site@BigQ.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )

main/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from main import forms


# Create your views here.
class ContactUsView(FormView):
    template_name = 'contact_form.html'
    form_class = forms.ContactForm
    success_url = '/'
    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main/templates/about_us.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
    <h2>About us</h2>
    <P> BigQ is the the software company .<br>
    We will help you to bring your idea into reality in fast and most power full way.</P>
    </div>

{% endblock  %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta
name="viewport"
content="width=device-width, initial-scale=1, shrink-to-fit=
no">
<!-- Bootstrap CSS -->
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<title>BigQ</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
       <a class="navbar-brand" href="/">BigQ</a>
       <button
                   class="navbar-toggler"
                   type="button"
                   data-toggle="collapse"
                   data-target="#navbarSupportedContent">
           <span class="navbar-toggler-icon"></span>
       </button>
    <div
             class="collapse navbar-collapse"
             id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == "/" %}active{% endif %}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {% if request.path == "/about-us/" %}active{% endif %}">
                <a class="nav-link" href="/about-us/">About us</a>
            </li>
            <li class="nav-item {% if request.path == "/contact-us/" %}active{% endif %}">
                <a class="nav-link" href="/contact-us/">contact us</a>
            </li>

        </ul>
    </div>
</nav>


  {% block content %}
  {% endblock content %}
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

main/templates/contact_form.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
    <h2>Contact US</h2>
    <p>Please fill the form below to contact us </p>
    </div>


    <div class="container ">
        <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            {{ form.name.label_tag }}
                <input
                       type="text"
                       class="form-control {% if form.name.errors %}is-invalid{%endif %}"
                       id="id_name"
                       name="name"
                       placeholder="Your name"
                       value="{{ form.name.value|default:"" }}" >
            {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.errors }}
                    </div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label_tag }}
            <input
                       type="email"
                       class="form-control {% if form.name.errors %}is-invalid{%endif %}"
                       id="id_email"
                       name="email"
                       placeholder="example@example.com"
                       value="{{ form.email.value|default:"" }}" >
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
        {{ form.message.label_tag }}
            <textarea class="form-control {% if form.message.errors %}is-invalid{%endif %}"
                    id="id_message"
                    name="message"
                    rows="3">{{ form.message.value|default:""}}</textarea>
        {% if form.message.errors %}
        <div class="invalid-feedback">
        {{ form.message.errors }}
        </div>
        {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>



{% endblock content %}

main/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h2>Welcome Home </h2>
    </div>

{% endblock content %}